In [ ]:
## Setting connection with Postgres

In [9]:
pip install psycopg2-binary sqlalchemy pandas

Requirement already satisfied: psycopg2-binary in /usr/local/Cellar/jupyterlab/4.5.6_3/libexec/lib/python3.14/site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in /usr/local/Cellar/jupyterlab/4.5.6_3/libexec/lib/python3.14/site-packages (2.0.49)
Requirement already satisfied: pandas in /usr/local/Cellar/jupyterlab/4.5.6_3/libexec/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: greenlet>=1 in /usr/local/Cellar/jupyterlab/4.5.6_3/libexec/lib/python3.14/site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/Cellar/jupyterlab/4.5.6_3/libexec/lib/python3.14/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/Cellar/jupyterlab/4.5.6_3/libexec/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/Cellar/jupyterlab/4.5.6_3/libexec/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/Cellar/jupyterlab/4.5.6_3/libexec/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from sqlalchemy import create_engine
import pandas as pd
from urllib.parse import quote_plus

#Connection to Postgre SQL
engine = create_engine(
    f"postgresql+psycopg2://postgres:admin@localhost:5432/olist"
)

with engine.connect() as conn:
    print('Connection Established!')

Connection Established!

In [ ]:
## GROSS REVENUE AND VOLUME - Before reporting any number, we need to make sure that all orders analyzed are valid. Canceled orders cannot enter into the real revenue.
## WHAT IS THE GROSS REVENUE OF DELIVERED ORDERS?
## First, we need to familiarize with the data and find out what types of status a order can have. For that, we'll use SELECT DISTINCT to list every word used on the status column.

In [4]:
query = 'SELECT DISTINCT order_status FROM orders;'
df = pd.read_sql(query,engine)
df #Status found :'delivered'

  order_status
0      shipped
1  unavailable
2     invoiced
3      created
4     approved
5   processing
6    delivered
7     canceled

In [ ]:
## Now we sum the price and the freight values from all delivered orders to get the gross revenue.

In [10]:
query = """
Select SUM(price + freight_value) AS total_revenue
FROM orders_items oi
JOIN orders o
ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered';
"""
df = pd.read_sql(query, engine)
df

   total_revenue
0    15419773.75

In [ ]:
## HOW MANY ORDERS WERE DELIVERED VS CANCELED VS OTHER STATUS?
## Let's count the orders using CASE, so they'll be grouped by condition. If the status differs from delivered or canceled, it'll be grouped as Others.

In [11]:
query = """
SELECT 
CASE
	WHEN order_status = 'delivered' THEN 'Delivered'
	WHEN order_status = 'canceled' THEN 'Canceled'
	ELSE 'Others'
END AS category,
COUNT (*) AS total
FROM orders
GROUP BY category;
"""
df = pd.read_sql(query, engine)
df

    category  total
0  Delivered  96478
1   Canceled    625
2     Others   2338

In [ ]:
## WHAT'S THE AVERAGE TICKET?
## In a business and storytelling context, an average ticket or AOV (Average Order Value) measures the average amount of revenue earned per order transaction.
## The AVG function works with sum/quantity, i.e., a query builded with the desiring values will have the number of orders counted already.
# Since one order id can have n items linked to it, the GROUP BY is the most important part os this query, transforming n items prices into one single value per order.

In [12]:
query = """
SELECT ROUND(AVG(order_total)::numeric, 2) AS aov
FROM (
	SELECT 
		o.order_id,
		SUM(oi.price + oi.freight_value) AS order_total
	FROM orders_items oi
	JOIN orders o
 	ON oi.order_id = o.order_id
	WHERE o.order_status ='delivered'
	GROUP BY o.order_id);
"""
df = pd.read_sql(query, engine)
df

      aov
0  159.83